#!/bin/bash
cd $HOME/.ddnet/

## Unzip source code
sudo tar -zxvf $HOME/.ddnet/DDNet* 

## Remove the package zip package at end
sudo rm -r $HOME/.ddnet/DDNet*.tar.gz 

## Give permessions to folder to let the built-in update system work
sudo find $HOME/.ddnet/ -type d -exec chmod 777 {} \;
sudo find $HOME/.ddnet/ -type f -exec chmod 777 {} \;

## Copy all sources in .ddnet
sudo cp -r $HOME/.ddnet/DDNet*/* $HOME/.ddnet/
sudo rm -r $HOME/.ddnet/DDNet*/
sudo find $HOME/.ddnet/* -type d -exec chmod 777 {} \;
sudo find $HOME/.ddnet/* -type f -exec chmod 777 {} \;
